server:
  port: 9999
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.57.181.11:3306/typechatdb?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Mengtianyu0909.
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB  #??????
      max-request-size: 1024MB

# ????
mybatis-plus:
  mapper-locations: classpath:/mybatis/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# ??????
path:
  image: D:\typechat\image\
  video: D:\typechat\video\
  audio: D:\typechat\audio\
  file: D:\typechat\file\
ip:
  address: http://localhost/
